on: [push]

jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build native Quarkus app
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Install graalvm
        uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '20.0.0.java11'
      - name: Install native-image
        run: gu install native-image
      - name: Set version
        run: ./mvnw versions:set -DnewVersion="${{ github.event.release.tag_name }}"
      - name: Build native executable
        run: ./mvnw package -Dnative
      - name: Upload native executable
        id: upload-native-executable
        uses: actions/upload-release-asset@v1